### ISSUE TITLE
Call to Host.Stop could lead to a `NullReferenceException`

### ISSUE THREAD

**Issue by philippdolder** [Particular/dotnetTemplates#20]
https://github.com/Particular/dotnetTemplates/blob/e16ef9ced20b895a5b2a357801a33d57b0b68b93/src/Templates/NServiceBusWindowsService/Host.cs#L64

The above referenced line could lead to a null reference exception inside the .NET code that is taking care of the `await`. The used `?.` operator could return `null` which will cause the issue.

My proposed solution would be to replace this line with
`await (this.endpoint?.Stop() ?? Task.CompletedTask);` 
I'm assuming that `Task.CompletedTask` is available in the lowest supported version for the dotnet new templates.

I'm happy to provide the pull request to solve this, if the proposed solution is in your interest

**Comment by ramonsmits** [comment]
@philippdolder Doing that would not result in an error thus the method to be invoked without issues. Not sure is that is even the intent. @bording what do you think is the right behavior for Stop as I would not expect Stop to gracefully return when the endpoint property is null as it can only be null when Start failed so I probably would expect a the actual unhandled exception of an `InvalidOperationException`.

**Comment by bording** [comment]
@philippdolder You are correct that if `endpoint` was null at that point, that line would end up being `await null`, which would throw a `NullReferenceException`.

However, if you look at the rest of the code in the template, I'm not sure you'd actually be able to make that happen. `endpoint` gets assigned a value in `Host.Start`, and if the call to `Endpoint.Start` failed, it would have thrown an exception, which would be caught and `FailFast` would be called, killing the process.

The only way I can currently see being in the scenario you described would be if someone modified the code and called `Host.Stop` before calling `Host.Start`, but that's already something we'd consider an error anyway.

For completeness sake, we could make the change you're suggesting, however for 2 out of the 3 templates we have, we support them running on `net452`, and `Task.CompletedTask` doesn't exist there.

That means we'd need to make the line conditional so that the template system could pick the right line to use based on the chosen framework.

**Comment by philippdolder** [comment]
@bording then I'd think that just removing the null-coalescing operator would be the better way? Just to not confuse the reader 🤔 
No strong feelings about that though

**Comment by bording** [comment]
> @bording then I'd think that just removing the null-coalescing operator would be the better way? Just to not confuse the reader

Yeah, I had been thinking the same thing, we could probably just remove it completely.
